server:
  port: 8002

spring:
  application:
    name: taoyi-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou-product?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

